kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dlflow
subjects:
- kind: ServiceAccount
  name: dlflow
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: dlflow
  apiGroup: rbac.authorization.k8s.io
