apiVersion: v1
kind: ServiceAccount
metadata:
  name: df-operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlflow
  labels:
    app.kubernetes.io/name: {{ include "dlflow.name" . }}
    helm.sh/chart: {{ include "dlflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}